### ISSUE TITLE
如何在js模式下获取组件是否打开的bool值

### ISSUE THREAD

**Issue by sangthian** [jekorx/vue-img-viewr#2]
博主的这个组件我很喜欢，但是有个问题，如何在js模式下获取组件是否打开的bool值，希望在vue中能watch这个变量

**Comment by jekorx** [comment]
@sangthian 很高兴能够使用这个组件，你所描述的问题已经在新的版本中增加```onShow```方法实现，https://www.npmjs.com/package/vue-img-viewr
